const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNUP = 'USER_SIGNUP';
const USER_SIGNOUT = 'USER_SIGNOUT';
const USER_ADD_MY_LIST = 'USER_ADD_MY_LIST';
const USER_REMOVE_MY_LIST = 'USER_REMOVE_MY_LIST';

export { USER_SIGNIN, USER_SIGNUP, USER_SIGNOUT, USER_ADD_MY_LIST, USER_REMOVE_MY_LIST };